### ISSUE TITLE
incorrect subject labels (should fail)

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/niak#5]
In your circle.yml you pass "2" as --participant_label, yet your sample dataset features only subjects with labels "0274" and "0275". What's going on?

```
sample_test/
sample_test/sub-0274/
sample_test/sub-0274/ses-1/
sample_test/sub-0274/ses-1/func/
sample_test/sub-0274/ses-1/func/sub-0274_ses-1_task-rest_run-2_bold.nii.gz
sample_test/sub-0274/ses-1/func/sub-0274_ses-1_task-rest_run-1_bold.nii.gz
sample_test/sub-0274/ses-1/anat/
sample_test/sub-0274/ses-1/anat/sub-0274_ses-1_T1w.nii.gz
sample_test/sub-0275/
sample_test/sub-0275/ses-1/
sample_test/sub-0275/ses-1/func/
sample_test/sub-0275/ses-1/func/sub-0275_ses-1_task-rest_run-1_bold.nii.gz
sample_test/sub-0275/ses-1/anat/
sample_test/sub-0275/ses-1/anat/sub-0275_ses-1_T1w.nii.gz
sample_test/dataset_description.json
```

**Comment by lunebellec** [comment]
Alright, so @poquirion may have taken some liberty with the BIDS system. As I already told you, I find that the mandatory organization into individual/group analysis is quite limiting. So PO hacked it. Our "individual" analyses really are individual PSOM workers. They have simple IDs, 1, 2, etc. The "group" analysis is a PSOM manager / garbage collector and deamon (a process that monitors all other processes, and resurrect them if needed). Together, they can play any NIAK pipeline with arbitrary workflow structure, including but not limited to preprocessing. The subject IDs are used correctly in this pipeline. 

To implement this "hack" PO actually used the pyniak library to instantiate PSOM workers/manager etc, that he has developped for CBRAIN. I am personally quite pleased with that approach, as it leverages all the work we've put into making PSOM an efficient and generic pipeline execution engine. Please let us know if you think that approach to be viable moving forward, in which case we can close this issue.

**Comment by lunebellec** [comment]
@poquirion please correct me if I incorrectly represented what you've done.

**Comment by chrisgorgo** [comment]
The manager + set of workers way of running analyses is quite impressive and indeed a nice way to perform computations (especially for certain hardware architectures).

However, the hack you implemented requires handling this app in a completely different way than every other app defying the purpose of a common command line interface and execution scheme. It also changes the meaning of `--participant_label` making it even more confusing to the user. I would really appreciate if you could try to follow the execution scheme outlined at the meeting and implemented by all of the other apps. I understand it might feel "backwards" to you, but unfortunately finding consensus requires such steps. Think of the positive side though - by following the common execution scheme NIAK will be easier to integrate into more platforms, because it could be treated like every other BIDS App. It also does not mean you should abandon or refactor the manager/worker scheme (which is indeed the best fit for your architecture) - all that is needed for compatibility with BIDS App scheme is ability to run all per participant workflows (potentially in parallel) followed by group level analysis (those steps can be be repeated providing multiple map reduce operations).

I know that this simple map/reduce scheme is inferior to the multiple workers/manager scheme you use, but this was the compromise that was simplest to implement by all parties involved in this project. It would be great if NIAK could comply with it instead of requiring different treatment by the execution system.

This PR can help with implementing the required changes: https://github.com/BIDS-Apps/niak/pulls
The main difference from the current hack is that the participant  analyses are being run first followed by a group analysis and the `--participant_label` expects labels of participants (not worker IDs).

**Comment by lunebellec** [comment]
I am traveling at the moment. I will sit down with @poquirion next week and figure out how to best fix this. Sorry to be so non-compliant.

**Comment by poquirion** [comment]
Hello @chrisfilo

I will not go in the details of the niak pipelines,  but the `--participant_label` option will work as expected if provided with the subject label, its just that it can also work when given random user id like in the test. It is a hack but it does not make the app behave differently than what was discuss in the workshop. 

What I can do is to limit the possible input of   `--participant_label` to the subject range in the bids directory, in this way the worker id will mach the subject id 1 to 1, and limit the flexibility of the app so it cannot be used the way I did. Would that be OK? 

But in the end, even if I do not add that restriction, the app does comply to what was agreed on during the workshop.

**Comment by chrisgorgo** [comment]
The problem is not only what values users can provide to `--participant_label` but what a `participant` level analysis does. Right now If I run NIAK BIDS App with `participant /bids_folder /output_folder  --participant_label 01` arguments it will [infinitely wait for some master program to send it jobs](https://circleci.com/gh/BIDS-Apps/niak/36?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). 

If I do the same for every other BIDS App it will run the first level analysis for participant 01, store results (that could potentially be used by the group level) in /output_folder - **independently of having to run any other orchestration processes in parallel**.

Have a look at this PR https://github.com/BIDS-Apps/niak/pull/7 tests defined in it should be passing, but instead the participant level analysis hangs for ever and timeouts after 2h (presume because it does not get any jobs from a master group thread). In short - `participant` and `group` level processes will never run at the same time. `group` level will only be started when the `participant` finishes.

**Comment by poquirion** [comment]
I did not realized that the group computation _had_ to run at the end after the participant_label, I'll fix that.

**Comment by lunebellec** [comment]
We discussed with @poquirion . We are going to work on separate scripts for individual and group analysis, following the BIDS specs. There are other niak pipelines which do not follow this paradigm. I'll consider refactoring them as BIDS apps in the future.

**Comment by chrisgorgo** [comment]
Thank you - this is much, much appreciated.

**Comment by lunebellec** [comment]
After further discussion, @poquirion and I agreed on a solution. The individual apps will simply run full preprocessing pipelines for 1 subject, and there won't be a group app. There will be a bit of redundancy in the computations across individual apps, but not a lot. The main issue is that there will be one QC report per subject, with mostly useless metrics (most of them are based on the group average, which in this case will be each individual scan separately....). But this will do short term. At the end of the month I will refactor the NIAK preprocessing pipeline to separate the group jobs from individual analyses. That way we'll have one consolidated group report, like this one https://simexp.github.io/qc_cobre/registration.html 

At this stage we'll have a clean BIDS app, which will reproduce closely the behaviour of the niak pipeline, just with more basic parallelization capabilities.

**Comment by poquirion** [comment]
Fixed! However, for now the pipeline/bids-app does not have a group level computation offering. We will surely add this options in the near futur but we will need to refactor the pipeline code. In any case we can still deliver most of the pipeline feature by staying at the participant level.
