### ISSUE TITLE
pipeline prologue

### ISSUE THREAD

**Issue by lunebellec** [BIDS-Apps/niak#8]
Fitting the niak preprocessing pipelines into pure individual / group stages is pretty straightforward. There is however a small component of the pipeline that does not follow this logic. The pipeline starts by copying/resampling a number of templates at the resolution requested by the user. These templates are then fed in the individual pipelines. I see two ways to implement that: 
1. BIDS apps have a "prologue" stage before individual analyses run. 
2. I refactor my pipeline to duplicate the generation of templates for each subject. That is a bit inefficient, but not a big deal considering the amount of other outputs generated. 

@chrisfilo let me know what you think.

**Comment by chrisgorgo** [comment]
So in essence you start with a simple `group` level followed by a participant level. You can add this as an extra step (and document it in README - later this will also be available through Boutiques).

So basically you can prescribe that your app will have the following stages:
`group1` (copy/resample templates)
`participant2` (perform first level; can be run in parallel with `--participant_label` )
`group2` (aggregate from first level)

Does this make sense?

**Comment by lunebellec** [comment]
It does make sense. Will work on this with @poquirion and get back to you if we run into an issue. Thanks for the quick answer.
